version: '3'

services:

  api:
    container_name: flask
    build: 
      context: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app/
    restart: always

  db:
    container_name: postgres 
    build: 
      context: ./db
    ports:
      - "5432:5432"
    
